import { dirname } from 'path'; 
import { fileURLToPath } from 'url'; 
const __filename = fileURLToPath(import.meta.url); 
const __dirname = dirname(__filename);
import dotenv from 'dotenv';
import express from 'express';
import db from './config/connection.js';
import { ApolloServer } from '@apollo/server';
import { expressMiddleware } from '@apollo/server/express4';
import { typeDefs, resolvers } from './schemas/index.js';
import jwt from 'jsonwebtoken';
import path from 'path';
import { authenticateToken, AuthenticationError } from './services/auth.js';