import { dirname } from 'path'; 
import { fileURLToPath } from 'url'; 
import dotenv from 'dotenv';
import express from 'express';
import db from './config/connection.js';
import { ApolloServer } from '@apollo/server';
import { expressMiddleware } from '@apollo/server/express4';
import jwt from 'jsonwebtoken';
import path from 'path';
import { authenticateToken, AuthenticationError } from './services/auth.js';
